-- Canonical staff identity V1.
--
-- Invariants:
--   * public.users.id is the durable staff identity; a PIN is a mutable credential.
--   * retired PINs never become independent users and are never accepted by login.
--   * historical finance/order rows keep their row IDs, amounts, notes and
--     idempotency keys; only explicitly allow-listed identity fields are canonicalized.
--   * allocator owner fields are lifecycle tokens: expired reservations are
--     released, while terminal USED ownership is canonicalized deliberately.
--   * every merge/save operation is serialized and idempotent.

create schema if not exists private;

alter table public.users
  add column if not exists updated_at timestamptz not null default pg_catalog.now();

create or replace function private.set_staff_user_updated_at_v1()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.updated_at is not distinct from old.updated_at then
    new.updated_at := pg_catalog.clock_timestamp();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_staff_user_updated_at_v1 on public.users;
create trigger trg_staff_user_updated_at_v1
before update on public.users
for each row execute function private.set_staff_user_updated_at_v1();

create table if not exists private.staff_pin_aliases (
  alias_pin text primary key,
  canonical_user_id uuid not null references public.users(id) on delete restrict,
  current_pin_snapshot text not null,
  source_user_id uuid null,
  retired_at timestamptz not null default pg_catalog.now(),
  reason text not null,
  created_by_pin text not null,
  created_at timestamptz not null default pg_catalog.now(),
  constraint staff_pin_alias_digits_chk check (alias_pin ~ '^[0-9]{3,12}$'),
  constraint staff_pin_alias_not_current_chk check (alias_pin <> current_pin_snapshot)
);

create index if not exists staff_pin_aliases_user_idx
  on private.staff_pin_aliases(canonical_user_id, retired_at desc);

create table if not exists private.staff_identity_merge_log (
  id bigint generated by default as identity primary key,
  idempotency_key text not null unique,
  action text not null,
  canonical_user_id uuid null,
  source_user_id uuid null,
  old_pins text[] not null default '{}'::text[],
  new_pin text null,
  actor_pin text not null,
  request_payload jsonb not null default '{}'::jsonb,
  before_snapshot jsonb not null default '{}'::jsonb,
  after_snapshot jsonb not null default '{}'::jsonb,
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default pg_catalog.now(),
  constraint staff_identity_merge_action_chk check (
    action in ('CANONICALIZE', 'MERGE', 'CREATE', 'UPDATE', 'DEACTIVATE', 'REACTIVATE')
  )
);

alter table private.staff_pin_aliases enable row level security;
alter table private.staff_identity_merge_log enable row level security;

-- Device approval administration is server-only. Remove legacy browser-write
-- policies/ACLs before the serverized staff API starts using canonical UUIDs.
alter table public.tepiha_user_devices enable row level security;
alter table public.tepiha_device_approvals enable row level security;
drop policy if exists anon_insert_devices on public.tepiha_user_devices;
drop policy if exists anon_select_devices on public.tepiha_user_devices;
drop policy if exists anon_update_devices on public.tepiha_user_devices;
drop policy if exists "deny anon" on public.tepiha_user_devices;
revoke all on table public.tepiha_user_devices from public, anon, authenticated;
revoke all on table public.tepiha_device_approvals from public, anon, authenticated;
revoke all on sequence public.tepiha_device_approvals_id_seq from public, anon, authenticated;
grant all on table public.tepiha_user_devices to service_role;
grant all on table public.tepiha_device_approvals to service_role;
grant all on sequence public.tepiha_device_approvals_id_seq to service_role;

revoke all on table private.staff_pin_aliases from public, anon, authenticated;
revoke all on table private.staff_identity_merge_log from public, anon, authenticated;
revoke all on sequence private.staff_identity_merge_log_id_seq from public, anon, authenticated;

-- Do not change existing private-schema ACLs here: other deployed RPCs already
-- depend on that shared schema. Object ACLs below are the security boundary for
-- the new identity records and helpers.
grant usage on schema private to service_role;
grant select, insert, update, delete on table private.staff_pin_aliases to service_role;
grant select, insert on table private.staff_identity_merge_log to service_role;
grant usage, select on sequence private.staff_identity_merge_log_id_seq to service_role;

create or replace function private.staff_normalize_name_v1(p_name text)
returns text
language sql
immutable
set search_path = ''
as $$
  select pg_catalog.lower(
    pg_catalog.regexp_replace(pg_catalog.btrim(coalesce(p_name, '')), '\s+', ' ', 'g')
  );
$$;

create or replace function private.staff_role_rank_v1(p_role text)
returns integer
language sql
immutable
set search_path = ''
as $$
  select case pg_catalog.upper(pg_catalog.btrim(coalesce(p_role,'')))
    when 'SUPERADMIN' then 50
    when 'OWNER' then 40
    when 'PRONAR' then 40
    when 'ADMIN_MASTER' then 30
    when 'ADMIN' then 20
    when 'DISPATCH' then 10
    when 'PUNTOR' then 0
    when 'TRANSPORT' then 0
    else -1
  end;
$$;

create or replace function private.guard_staff_pin_alias_v1()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('staff_identity_pin_registry_v1',0)
  );
  new.alias_pin := pg_catalog.btrim(coalesce(new.alias_pin, ''));
  new.current_pin_snapshot := pg_catalog.btrim(coalesce(new.current_pin_snapshot, ''));

  if exists (
    select 1 from public.users u where pg_catalog.btrim(u.pin) = new.alias_pin
  ) then
    raise exception 'STAFF_ALIAS_COLLIDES_WITH_CURRENT_PIN:%', new.alias_pin;
  end if;

  if not exists (
    select 1 from public.users u where u.id = new.canonical_user_id
  ) then
    raise exception 'STAFF_ALIAS_CANONICAL_USER_NOT_FOUND:%', new.canonical_user_id;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_guard_staff_pin_alias_v1 on private.staff_pin_aliases;
create trigger trg_guard_staff_pin_alias_v1
before insert or update on private.staff_pin_aliases
for each row execute function private.guard_staff_pin_alias_v1();

create or replace function private.guard_staff_current_pin_reuse_v1()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('staff_identity_pin_registry_v1',0)
  );
  if tg_op = 'INSERT' then
    if exists (
      select 1 from private.staff_pin_aliases a
      where a.alias_pin = pg_catalog.btrim(new.pin)
    ) then raise exception 'STAFF_PIN_IS_RETIRED:%', new.pin; end if;
  elsif new.pin is distinct from old.pin then
    if exists (
      select 1 from private.staff_pin_aliases a
      where a.alias_pin = pg_catalog.btrim(new.pin)
    ) then raise exception 'STAFF_PIN_IS_RETIRED:%', new.pin; end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_guard_staff_current_pin_reuse_v1 on public.users;
create trigger trg_guard_staff_current_pin_reuse_v1
before insert or update of pin on public.users
for each row execute function private.guard_staff_current_pin_reuse_v1();

create or replace function private.staff_identity_json_canonicalize_v1(
  p_value jsonb,
  p_old_pins text[],
  p_new_pin text,
  p_old_user_ids text[] default '{}'::text[],
  p_new_transport_id text default null
)
returns jsonb
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_type text;
  v_key text;
  v_item jsonb;
  v_text text;
  v_result jsonb;
  v_pin_keys constant text[] := array[
    'actor_pin','accepted_by_pin','approved_by_pin','assigned_driver_pin','assigned_to_pin',
    'audited_by_pin','base_driver_notified_by','base_driver_notified_by_pin','beneficiary_pin',
    'brought_by_pin','cancelled_by_pin','changed_by_pin','closed_by_pin','completed_by_pin',
    'created_by_pin','decided_by_pin','delivered_by','delivered_by_pin','dispatch_pin',
    'driver_pin','finalized_by_pin','found_by','handed_by_pin','last_payment_by_pin','opened_by_pin',
    'paid_by_pin','pickup_confirmed_by_pin','posted_by_pin','prepaid_by_pin','ready_by_pin',
    'ready_note_by_pin','recovered_by_pin','released_by_pin','requested_pin','resolved_by_pin',
    'responsible_worker_pin','reviewed_by_pin','transport_pin','updated_by','updated_by_pin',
    'worker_pin','wrapped_by','by_pin','pin'
  ];
  v_id_keys constant text[] := array[
    'assigned_driver_id','cancelled_by_transport_id','delivered_by_transport_id','driver_id',
    'tid','transport_id','transport_user_id'
  ];
begin
  if p_value is null then return null; end if;
  v_type := pg_catalog.jsonb_typeof(p_value);

  if v_type = 'object' then
    v_result := '{}'::jsonb;
    for v_key, v_item in select key, value from pg_catalog.jsonb_each(p_value)
    loop
      if pg_catalog.jsonb_typeof(v_item) in ('string', 'number') then
        v_text := v_item #>> '{}';
        if v_key = any(v_pin_keys) and v_text = any(coalesce(p_old_pins, '{}'::text[])) then
          v_item := pg_catalog.to_jsonb(p_new_pin);
        elsif v_key = any(v_id_keys)
          and (
            v_text = any(coalesce(p_old_user_ids, '{}'::text[]))
            or (v_key in ('transport_id','tid') and v_text = any(coalesce(p_old_pins, '{}'::text[])))
          )
          and p_new_transport_id is not null then
          v_item := pg_catalog.to_jsonb(p_new_transport_id);
        end if;
      elsif pg_catalog.jsonb_typeof(v_item) in ('object', 'array') then
        v_item := private.staff_identity_json_canonicalize_v1(
          v_item, p_old_pins, p_new_pin, p_old_user_ids, p_new_transport_id
        );
      end if;
      v_result := v_result || pg_catalog.jsonb_build_object(v_key, v_item);
    end loop;
    return v_result;
  elsif v_type = 'array' then
    select coalesce(
      pg_catalog.jsonb_agg(
        private.staff_identity_json_canonicalize_v1(
          x.value, p_old_pins, p_new_pin, p_old_user_ids, p_new_transport_id
        ) order by x.ordinality
      ),
      '[]'::jsonb
    ) into v_result
    from pg_catalog.jsonb_array_elements(p_value) with ordinality as x(value, ordinality);
    return v_result;
  end if;

  return p_value;
end;
$$;

create or replace function private.staff_update_pin_column_if_present_v1(
  p_table_name text,
  p_column_name text,
  p_old_pins text[],
  p_new_pin text
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_table regclass;
  v_rows integer := 0;
  v_has_old boolean := false;
begin
  v_table := pg_catalog.to_regclass(p_table_name);
  if v_table is null then return 0; end if;

  if not exists (
    select 1
    from pg_catalog.pg_attribute a
    where a.attrelid = v_table
      and a.attname = p_column_name
      and a.attnum > 0
      and not a.attisdropped
  ) then
    return 0;
  end if;

  execute pg_catalog.format(
    'update %s set %I = $1 where %I = any($2)',
    v_table, p_column_name, p_column_name
  ) using p_new_pin, p_old_pins;
  get diagnostics v_rows = row_count;

  execute pg_catalog.format(
    'select exists(select 1 from %s where %I=any($1))',
    v_table,p_column_name
  ) into v_has_old using p_old_pins;
  if v_has_old then
    raise exception 'STAFF_STRUCTURED_PIN_POSTCHECK_FAILED:%.%',p_table_name,p_column_name;
  end if;
  return v_rows;
end;
$$;

create or replace function private.staff_financial_checksum_v1(p_pins text[])
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select pg_catalog.jsonb_build_object(
    'arka_created_count', (select pg_catalog.count(*) from public.arka_pending_payments p where p.created_by_pin = any(p_pins)),
    'arka_created_amount', (select pg_catalog.round(coalesce(pg_catalog.sum(p.amount),0),2) from public.arka_pending_payments p where p.created_by_pin = any(p_pins)),
    'handoff_count', (select pg_catalog.count(*) from public.cash_handoffs h where h.worker_pin = any(p_pins)),
    'handoff_amount', (select pg_catalog.round(coalesce(pg_catalog.sum(h.amount),0),2) from public.cash_handoffs h where h.worker_pin = any(p_pins)),
    'bonus_count', (select pg_catalog.count(*) from public.base_ready_bonuses b where b.worker_pin = any(p_pins)),
    'bonus_amount', (select pg_catalog.round(coalesce(pg_catalog.sum(b.amount),0),2) from public.base_ready_bonuses b where b.worker_pin = any(p_pins)),
    'payroll_count', (select pg_catalog.count(*) from public.payroll_month_close_items i where i.worker_pin = any(p_pins)),
    'payroll_net', (select pg_catalog.round(coalesce(pg_catalog.sum(i.net_pay),0),2) from public.payroll_month_close_items i where i.worker_pin = any(p_pins)),
    'transport_batch_count', (select pg_catalog.count(*) from public.transport_payment_batches b where b.created_by_pin = any(p_pins)),
    'transport_batch_amount', (select pg_catalog.round(coalesce(pg_catalog.sum(b.amount_applied),0),2) from public.transport_payment_batches b where b.created_by_pin = any(p_pins))
  );
$$;

create or replace function private.canonicalize_staff_history_v1(
  p_canonical_user_id uuid,
  p_old_pins text[],
  p_new_pin text,
  p_old_user_ids uuid[] default '{}'::uuid[]
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_pair record;
  v_rows integer := 0;
  v_total_rows integer := 0;
  v_order_rows integer := 0;
  v_transport_rows integer := 0;
  v_old_id_texts text[] := '{}'::text[];
  v_transport_id text;
  v_canonical_role text;
  v_approval public.tepiha_device_approvals%rowtype;
  v_current_approval public.tepiha_device_approvals%rowtype;
  v_authoritative_device public.tepiha_user_devices%rowtype;
  v_has_current_approval boolean;
  v_has_authoritative_device boolean;
  v_prev_maintenance text := pg_catalog.current_setting('tepiha.finance_maintenance', true);
begin
  if p_canonical_user_id is null then raise exception 'STAFF_CANONICAL_USER_ID_REQUIRED'; end if;
  if p_new_pin is null or pg_catalog.btrim(p_new_pin) = '' then raise exception 'STAFF_NEW_PIN_REQUIRED'; end if;

  -- UUID identity keys always converge on users.id. transport_id/tid are
  -- compatibility aliases and must never select a second durable identity.
  select u.id::text,u.role
  into v_transport_id,v_canonical_role
  from public.users u
  where u.id = p_canonical_user_id;
  if not found then raise exception 'STAFF_CANONICAL_USER_NOT_FOUND:%', p_canonical_user_id; end if;

  select coalesce(pg_catalog.array_agg(x::text), '{}'::text[])
  into v_old_id_texts
  from pg_catalog.unnest(coalesce(p_old_user_ids, '{}'::uuid[])) as x;

  perform pg_catalog.set_config('tepiha.finance_maintenance', 'on', true);

  -- BASE allocator rows have lifecycle meaning. Expired, unreferenced retired-
  -- identity reservations are released (never moved into the current PIN's
  -- quota); terminal USED ownership is historical identity and is canonicalized.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('tepiha_pranimi_code_allocator_v39_1')
  );

  update public.offline_code_leases l
  set status='expired', released_at=coalesce(l.released_at,pg_catalog.now()),
      updated_at=pg_catalog.now(),
      metadata=coalesce(l.metadata,'{}'::jsonb)
        || pg_catalog.jsonb_build_object('expired_reason','retired_staff_pool_release')
  where l.scope='base'
    and l.status in ('available','assigned')
    and l.expires_at is not null
    and l.expires_at<=pg_catalog.now()
    and exists(
      select 1 from public.base_code_pool b
      where b.code::text=l.code
        and b.status='reserved'
        and (b.owner_id=any(p_old_pins) or b.reserved_by=any(p_old_pins))
        and b.lease_expires_at is not null
        and b.lease_expires_at <= pg_catalog.now()
        and not exists(
          select 1 from public.offline_code_leases active_l
          where active_l.scope='base' and active_l.code=b.code::text
            and active_l.status in ('available','assigned')
            and (active_l.expires_at is null or active_l.expires_at>pg_catalog.now())
        )
        and not exists(select 1 from public.orders o where o.code::text=b.code::text)
        and not exists(select 1 from public.clients c where c.code::text=b.code::text)
    );
  get diagnostics v_rows = row_count;
  v_total_rows := v_total_rows + v_rows;

  update public.base_code_pool b
  set status='available', owner_id='', reserved_by=null, reserved_at=null,
      lease_expires_at=null, draft_session_id=null,
      draft_has_meaningful_work=false
  where b.status='reserved'
    and (b.owner_id=any(p_old_pins) or b.reserved_by=any(p_old_pins))
    and b.lease_expires_at is not null
    and b.lease_expires_at <= pg_catalog.now()
    and not exists(
      select 1 from public.offline_code_leases active_l
      where active_l.scope='base' and active_l.code=b.code::text
        and active_l.status in ('available','assigned')
        and (active_l.expires_at is null or active_l.expires_at>pg_catalog.now())
    )
    and not exists(select 1 from public.orders o where o.code::text=b.code::text)
    and not exists(select 1 from public.clients c where c.code::text=b.code::text);
  get diagnostics v_rows = row_count;
  v_total_rows := v_total_rows + v_rows;

  if exists(
    select 1 from public.base_code_pool b
    where b.status='reserved'
      and (b.owner_id=any(p_old_pins) or b.reserved_by=any(p_old_pins))
  ) then raise exception 'STAFF_BASE_RESERVATION_LIFECYCLE_CONFLICT'; end if;

  update public.base_code_pool b
  set owner_id=p_new_pin
  where b.status='used' and b.owner_id=any(p_old_pins);
  get diagnostics v_rows = row_count;
  v_total_rows := v_total_rows + v_rows;

  update public.base_code_pool b
  set owner_id=''
  where b.status='available' and b.owner_id=any(p_old_pins);
  get diagnostics v_rows = row_count;
  v_total_rows := v_total_rows + v_rows;

  -- Expired offline leases are terminalized before their identity snapshot is
  -- canonicalized. Live leases were rejected by merge_staff_identity_v1.
  update public.offline_code_leases l
  set status='expired', released_at=coalesce(l.released_at,pg_catalog.now()),
      updated_at=pg_catalog.now(),
      metadata=coalesce(l.metadata,'{}'::jsonb)
        || pg_catalog.jsonb_build_object('expired_reason','staff_identity_retired')
  where l.owner_id=any(p_old_pins || v_old_id_texts)
    and l.status in ('available','assigned')
    and l.expires_at <= pg_catalog.now();
  get diagnostics v_rows = row_count;
  v_total_rows := v_total_rows + v_rows;

  update public.offline_code_leases l
  set owner_id=case when l.scope='transport' then p_canonical_user_id::text else p_new_pin end,
      updated_at=pg_catalog.now()
  where l.owner_id=any(p_old_pins || v_old_id_texts)
    and not (
      l.status in ('available','assigned')
      and (l.expires_at is null or l.expires_at>pg_catalog.now())
    );
  get diagnostics v_rows = row_count;
  v_total_rows := v_total_rows + v_rows;

  if exists(
    select 1 from public.transport_code_pool t
    where t.owner_id=any(p_old_pins || v_old_id_texts) and t.status<>'used'
  ) then raise exception 'STAFF_TRANSPORT_CODE_LIFECYCLE_CONFLICT'; end if;

  update public.transport_code_pool t
  set owner_id=p_canonical_user_id::text
  where t.status='used' and t.owner_id=any(p_old_pins || v_old_id_texts);
  get diagnostics v_rows = row_count;
  v_total_rows := v_total_rows + v_rows;

  for v_pair in
    select * from (values
      ('public.arka_advance_budget_links','posted_by_pin'),
      ('public.arka_cycles','opened_by_pin'),
      ('public.arka_cycles','closed_by_pin'),
      ('public.arka_daily_close_items','worker_pin'),
      ('public.arka_expense_decisions','driver_pin'),
      ('public.arka_expense_decisions','beneficiary_pin'),
      ('public.arka_expense_decisions','decided_by_pin'),
      ('public.arka_expense_decisions','cancelled_by_pin'),
      ('public.arka_expense_decisions','finalized_by_pin'),
      ('public.arka_payment_exclusions','created_by_pin'),
      ('public.arka_payment_exclusions','cancelled_by_pin'),
      ('public.arka_pending_payments','created_by_pin'),
      ('public.arka_pending_payments','approved_by_pin'),
      ('public.arka_pending_payments','handed_by_pin'),
      ('public.base_code_pool','used_by_pin'),
      ('public.base_ready_bonus_config','updated_by_pin'),
      ('public.base_ready_bonuses','worker_pin'),
      ('public.cash_handoff_expense_decisions','driver_pin'),
      ('public.cash_handoff_expense_decisions','beneficiary_pin'),
      ('public.cash_handoff_expense_decisions','decided_by_pin'),
      ('public.cash_handoff_expense_decisions','cancelled_by_pin'),
      ('public.cash_handoff_items','released_by_pin'),
      ('public.cash_handoffs','worker_pin'),
      ('public.cash_handoffs','dispatch_pin'),
      ('public.company_budget_ledger','created_by_pin'),
      ('public.company_budget_ledger','approved_by_pin'),
      ('public.company_budget_moves','created_by_pin'),
      ('public.company_budget_moves','worker_pin'),
      ('public.company_budget_moves','accepted_by_pin'),
      ('public.company_fixed_expenses','created_by_pin'),
      ('public.manual_budget_adjustments','created_by_pin'),
      ('public.manual_budget_adjustments','cancelled_by_pin'),
      ('public.payroll_month_close_items','worker_pin'),
      ('public.payroll_month_close_items','accepted_by_worker_pin'),
      ('public.payroll_month_closes','created_by_pin'),
      ('public.tepiha_user_devices','requested_pin'),
      ('public.transport_delivery_events','actor_pin'),
      ('public.transport_payment_batches','created_by_pin'),
      ('public.transport_receivables','created_by_pin'),
      ('public.users','pay_updated_by_pin'),
      ('public.worker_compensation_audit','worker_pin'),
      ('public.worker_compensation_audit','changed_by_pin'),
      ('public.worker_employment_terms','created_by_pin')
    ) as x(table_name, column_name)
  loop
    v_rows := private.staff_update_pin_column_if_present_v1(
      v_pair.table_name, v_pair.column_name, p_old_pins, p_new_pin
    );
    v_total_rows := v_total_rows + v_rows;
  end loop;

  -- The UUID-linked user-device row is authoritative. Mirror approvals are
  -- re-keyed without carrying approval from a retired PIN: a missing or false
  -- authoritative link becomes false, while a true link remains true. Existing
  -- (current PIN, device) rows are reconciled before deleting the duplicate.
  for v_approval in
    select a.*
    from public.tepiha_device_approvals a
    where a.pin=any(p_old_pins)
    order by a.id
    for update
  loop
    select * into v_authoritative_device
    from public.tepiha_user_devices d
    where d.user_id=p_canonical_user_id and d.device_id=v_approval.device_id
    order by d.created_at desc
    limit 1;
    v_has_authoritative_device := found;

    select * into v_current_approval
    from public.tepiha_device_approvals a
    where a.pin=p_new_pin and a.device_id=v_approval.device_id
    limit 1
    for update;
    v_has_current_approval := found;

    if v_has_current_approval then
      update public.tepiha_device_approvals a
      set approved=case when v_has_authoritative_device
                          then v_authoritative_device.is_approved else false end,
          approved_at=case
            when v_has_authoritative_device and v_authoritative_device.is_approved
              then coalesce(v_authoritative_device.approved_at,a.approved_at,v_approval.approved_at)
            else null end,
          approved_by=case
            when v_has_authoritative_device and v_authoritative_device.is_approved
              then coalesce(v_authoritative_device.approved_by,a.approved_by,v_approval.approved_by)
            else null end,
          role=coalesce(
            case when v_has_authoritative_device then v_authoritative_device.requested_role end,
            a.role,v_approval.role,v_canonical_role
          ),
          label=coalesce(a.label,v_approval.label),
          last_seen_at=greatest(a.last_seen_at,v_approval.last_seen_at)
      where a.id=v_current_approval.id;
      delete from public.tepiha_device_approvals where id=v_approval.id;
      v_total_rows := v_total_rows + 2;
    else
      update public.tepiha_device_approvals a
      set pin=p_new_pin,
          approved=case when v_has_authoritative_device
                          then v_authoritative_device.is_approved else false end,
          approved_at=case
            when v_has_authoritative_device and v_authoritative_device.is_approved
              then coalesce(v_authoritative_device.approved_at,a.approved_at)
            else null end,
          approved_by=case
            when v_has_authoritative_device and v_authoritative_device.is_approved
              then coalesce(v_authoritative_device.approved_by,a.approved_by)
            else null end,
          role=coalesce(
            case when v_has_authoritative_device then v_authoritative_device.requested_role end,
            a.role,v_canonical_role
          )
      where a.id=v_approval.id;
      v_total_rows := v_total_rows + 1;
    end if;
  end loop;

  -- Exact structured JSON identity keys only. The recursive walker never
  -- rewrites notes, phones, client data, free text, or idempotency keys.
  --
  -- These are maintenance-only identity rewrites, not business transitions.
  -- Normal order triggers would otherwise upsert clients, renew offline code
  -- leases, recalculate bonuses, capture locations and alter updated_at. Require
  -- every user trigger to be enabled before entry, then suppress USER triggers
  -- only for the two controlled JSON updates. Constraint triggers stay active.
  -- The exception block restores the known-good trigger state before rethrowing;
  -- the surrounding transaction also rolls back every write on failure.
  if exists (
    select 1 from pg_catalog.pg_trigger t
    where t.tgrelid in ('public.orders'::pg_catalog.regclass,
                        'public.transport_orders'::pg_catalog.regclass)
      and not t.tgisinternal and t.tgenabled <> 'O'
  ) then raise exception 'STAFF_ORDER_TRIGGER_STATE_UNSAFE'; end if;

  begin
    execute 'alter table public.orders disable trigger user';
    execute 'alter table public.transport_orders disable trigger user';

    with candidates as materialized (
      select o.id,
        private.staff_identity_json_canonicalize_v1(
          o.data, p_old_pins, p_new_pin, v_old_id_texts, v_transport_id
        ) as next_data
      from public.orders o
    )
    update public.orders o
    set data = c.next_data
    from candidates c
    where o.id = c.id and o.data is distinct from c.next_data;
    get diagnostics v_order_rows = row_count;

    with candidates as materialized (
      select o.id,
        private.staff_identity_json_canonicalize_v1(
          o.data, p_old_pins, p_new_pin, v_old_id_texts, v_transport_id
        ) as next_data
      from public.transport_orders o
    )
    update public.transport_orders o
    set data = c.next_data
    from candidates c
    where o.id = c.id and o.data is distinct from c.next_data;
    get diagnostics v_transport_rows = row_count;

    execute 'alter table public.transport_orders enable trigger user';
    execute 'alter table public.orders enable trigger user';
  exception when others then
    execute 'alter table public.transport_orders enable trigger user';
    execute 'alter table public.orders enable trigger user';
    raise;
  end;

  if p_old_user_ids is not null and pg_catalog.cardinality(p_old_user_ids) > 0 then
    update public.payroll_month_close_items
    set worker_id = p_canonical_user_id
    where worker_id = any(p_old_user_ids);
    get diagnostics v_rows = row_count;
    v_total_rows := v_total_rows + v_rows;
  end if;

  perform pg_catalog.set_config(
    'tepiha.finance_maintenance', coalesce(v_prev_maintenance, ''), true
  );

  return pg_catalog.jsonb_build_object(
    'structured_rows', v_total_rows,
    'order_json_rows', v_order_rows,
    'transport_json_rows', v_transport_rows
  );
end;
$$;

create or replace function public.resolve_staff_identity_v1(p_pin text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user public.users%rowtype;
  v_alias private.staff_pin_aliases%rowtype;
  v_match text := pg_catalog.btrim(coalesce(p_pin, ''));
begin
  if v_match = '' then raise exception 'STAFF_PIN_REQUIRED'; end if;

  select * into v_user from public.users u where u.pin = v_match limit 1;
  if found then
    return pg_catalog.jsonb_build_object(
      'ok', true, 'user_id', v_user.id, 'pin', v_user.pin, 'name', v_user.name,
      'role', v_user.role, 'is_active', v_user.is_active,
      'matched_pin', v_match, 'is_alias', false
    );
  end if;

  select * into v_alias
  from private.staff_pin_aliases a
  where a.alias_pin = v_match;
  if not found then return pg_catalog.jsonb_build_object('ok', false, 'reason', 'STAFF_PIN_NOT_FOUND'); end if;

  select * into v_user from public.users u where u.id = v_alias.canonical_user_id;
  if not found then raise exception 'STAFF_ALIAS_ORPHANED:%', v_match; end if;

  return pg_catalog.jsonb_build_object(
    'ok', true, 'user_id', v_user.id, 'pin', v_user.pin, 'name', v_user.name,
    'role', v_user.role, 'is_active', v_user.is_active,
    'matched_pin', v_match, 'is_alias', true, 'retired_at', v_alias.retired_at
  );
end;
$$;

revoke execute on function public.resolve_staff_identity_v1(text)
from public, anon, authenticated;
grant execute on function public.resolve_staff_identity_v1(text) to service_role;

comment on function public.resolve_staff_identity_v1(text) is
  'Service-role-only history resolver. Retired aliases are never a login credential.';

create or replace function public.merge_staff_identity_v1(
  p_actor_pin text,
  p_canonical_user_id uuid,
  p_source_user_id uuid,
  p_expected_canonical_pin text,
  p_expected_source_pin text,
  p_retired_pins text[],
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor public.users%rowtype;
  v_canonical public.users%rowtype;
  v_source public.users%rowtype;
  v_existing private.staff_identity_merge_log%rowtype;
  v_old_pins text[];
  v_request jsonb;
  v_before_checksum jsonb;
  v_after_checksum jsonb;
  v_history jsonb;
  v_before jsonb;
  v_after jsonb;
  v_result jsonb;
  v_alias text;
  v_source_ids uuid[] := '{}'::uuid[];
  v_source_id_texts text[] := '{}'::text[];
  v_actor_rank integer := 0;
begin
  if pg_catalog.btrim(coalesce(p_idempotency_key,'')) = '' then
    raise exception 'STAFF_IDEMPOTENCY_KEY_REQUIRED';
  end if;
  if p_canonical_user_id is null then raise exception 'STAFF_CANONICAL_USER_ID_REQUIRED'; end if;

  select coalesce(pg_catalog.array_agg(distinct pin order by pin), '{}'::text[])
  into v_old_pins
  from (
    select pg_catalog.btrim(x) pin
    from pg_catalog.unnest(coalesce(p_retired_pins, '{}'::text[])) x
    where pg_catalog.btrim(coalesce(x,'')) <> ''
    union
    select pg_catalog.btrim(p_expected_source_pin)
    where pg_catalog.btrim(coalesce(p_expected_source_pin,'')) <> ''
  ) q;

  v_request := pg_catalog.jsonb_build_object(
    'canonical_user_id', p_canonical_user_id,
    'source_user_id', p_source_user_id,
    'expected_canonical_pin', pg_catalog.btrim(coalesce(p_expected_canonical_pin,'')),
    'expected_source_pin', pg_catalog.btrim(coalesce(p_expected_source_pin,'')),
    'retired_pins', v_old_pins
  );

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('staff_identity_idem:' || p_idempotency_key, 0)
  );
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('staff_identity_pin_registry_v1',0)
  );

  select * into v_existing
  from private.staff_identity_merge_log l
  where l.idempotency_key = p_idempotency_key;
  if found then
    if v_existing.action not in ('CANONICALIZE','MERGE')
       or v_existing.request_payload is distinct from v_request then
      raise exception 'STAFF_IDEMPOTENCY_CONFLICT';
    end if;
    return v_existing.result;
  end if;

  select * into v_actor
  from public.users u
  where u.pin = pg_catalog.btrim(coalesce(p_actor_pin,''))
    and u.is_active is true
  limit 1;
  v_actor_rank := private.staff_role_rank_v1(v_actor.role);
  if not found or v_actor_rank < 20 then
    raise exception 'STAFF_MANAGER_ONLY';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('staff_identity_user:' || p_canonical_user_id::text, 0)
  );
  if p_source_user_id is not null then
    perform pg_catalog.pg_advisory_xact_lock(
      pg_catalog.hashtextextended('staff_identity_user:' || p_source_user_id::text, 0)
    );
  end if;

  select * into v_canonical
  from public.users u where u.id = p_canonical_user_id for update;
  if not found then raise exception 'STAFF_CANONICAL_USER_NOT_FOUND'; end if;
  if v_canonical.pin is distinct from pg_catalog.btrim(p_expected_canonical_pin) then
    raise exception 'STAFF_CANONICAL_PIN_STALE expected=% actual=%', p_expected_canonical_pin, v_canonical.pin;
  end if;
  if v_canonical.is_active is not true then raise exception 'STAFF_CANONICAL_USER_NOT_ACTIVE'; end if;
  if private.staff_role_rank_v1(v_canonical.role) > v_actor_rank then
    raise exception 'STAFF_ROLE_HIERARCHY_DENIED';
  end if;

  foreach v_alias in array v_old_pins loop
    if v_alias !~ '^[0-9]{3,12}$' then raise exception 'STAFF_RETIRED_PIN_INVALID:%', v_alias; end if;
    if v_alias = v_canonical.pin then raise exception 'STAFF_ALIAS_EQUALS_CURRENT_PIN:%', v_alias; end if;
    if exists (select 1 from public.users u where u.pin = v_alias and u.id <> coalesce(p_source_user_id, p_canonical_user_id)) then
      raise exception 'STAFF_ALIAS_OWNED_BY_OTHER_USER:%', v_alias;
    end if;
    if exists (
      select 1 from private.staff_pin_aliases a
      where a.alias_pin = v_alias
        and a.canonical_user_id<>p_canonical_user_id
        and (p_source_user_id is null or a.canonical_user_id<>p_source_user_id)
    ) then
      raise exception 'STAFF_ALIAS_OWNED_BY_OTHER_IDENTITY:%', v_alias;
    end if;
  end loop;

  if p_source_user_id is not null then
    if p_source_user_id = p_canonical_user_id then raise exception 'STAFF_SOURCE_EQUALS_CANONICAL'; end if;
    select * into v_source from public.users u where u.id = p_source_user_id for update;
    if not found then raise exception 'STAFF_SOURCE_USER_NOT_FOUND'; end if;
    if v_source.pin is distinct from pg_catalog.btrim(p_expected_source_pin) then
      raise exception 'STAFF_SOURCE_PIN_STALE expected=% actual=%', p_expected_source_pin, v_source.pin;
    end if;
    if v_source.is_active is true then raise exception 'STAFF_SOURCE_MUST_BE_INACTIVE'; end if;
    if private.staff_normalize_name_v1(v_source.name) <> private.staff_normalize_name_v1(v_canonical.name)
       or pg_catalog.upper(pg_catalog.btrim(coalesce(v_source.role,'')))
          <> pg_catalog.upper(pg_catalog.btrim(coalesce(v_canonical.role,''))) then
      raise exception 'STAFF_SOURCE_IDENTITY_MISMATCH';
    end if;
    v_source_ids := array[p_source_user_id];
    v_source_id_texts := array[p_source_user_id::text];

    select coalesce(pg_catalog.array_agg(distinct x order by x),'{}'::text[])
    into v_old_pins
    from (
      select p pin from pg_catalog.unnest(v_old_pins) p
      union
      select a.alias_pin from private.staff_pin_aliases a
      where a.canonical_user_id=p_source_user_id
    ) aliases(x);

    foreach v_alias in array v_old_pins loop
      if v_alias=v_canonical.pin then raise exception 'STAFF_ALIAS_EQUALS_CURRENT_PIN:%',v_alias; end if;
      if exists(
        select 1 from public.users u
        where u.pin=v_alias and u.id not in (p_canonical_user_id,p_source_user_id)
      ) then raise exception 'STAFF_ALIAS_OWNED_BY_OTHER_USER:%',v_alias; end if;
      if exists(
        select 1 from private.staff_pin_aliases a
        where a.alias_pin=v_alias
          and a.canonical_user_id not in (p_canonical_user_id,p_source_user_id)
      ) then raise exception 'STAFF_ALIAS_OWNED_BY_OTHER_IDENTITY:%',v_alias; end if;
    end loop;
  end if;

  -- Active/indeterminate allocator ownership must be explicitly resolved before
  -- a PIN move. Expired, unreferenced BASE reservations are safely released by
  -- canonicalize_staff_history_v1; terminal USED ownership is canonicalized.
  if exists (
    select 1 from public.offline_code_leases l
    where l.owner_id = any(v_old_pins || v_source_id_texts)
      and l.status in ('available','assigned')
      and (l.expires_at is null or l.expires_at > pg_catalog.now())
  ) then raise exception 'STAFF_ACTIVE_OFFLINE_LEASE_CONFLICT'; end if;
  if exists (
    select 1 from public.base_code_pool b
    where (b.owner_id = any(v_old_pins) or b.reserved_by = any(v_old_pins))
      and b.status = 'reserved'
      and (b.lease_expires_at is null or b.lease_expires_at > pg_catalog.now())
  ) then raise exception 'STAFF_ACTIVE_BASE_RESERVATION_CONFLICT'; end if;

  if exists (
    select 1
    from public.payroll_month_close_items old_i
    join public.payroll_month_close_items new_i
      on new_i.close_id = old_i.close_id
     and new_i.worker_pin = v_canonical.pin
     and new_i.id <> old_i.id
    where old_i.worker_pin = any(v_old_pins)
  ) then raise exception 'STAFF_PAYROLL_PIN_CONFLICT'; end if;

  -- tepiha_device_approvals is a security mirror. The history helper re-keys it
  -- only after synchronizing approved=false/true from the authoritative UUID-
  -- linked tepiha_user_devices row; unmatched mirrors become false.

  if p_source_user_id is not null and exists (
    select 1
    from public.worker_employment_terms s
    join public.worker_employment_terms c
      on c.user_id = p_canonical_user_id and c.effective_from = s.effective_from
    where s.user_id = p_source_user_id
      and (pg_catalog.to_jsonb(s) - array['id','user_id','created_at']::text[])
          is distinct from (pg_catalog.to_jsonb(c) - array['id','user_id','created_at']::text[])
  ) then raise exception 'STAFF_EMPLOYMENT_TERMS_CONFLICT'; end if;

  v_before_checksum := private.staff_financial_checksum_v1(v_old_pins || array[v_canonical.pin]);
  v_before := pg_catalog.jsonb_build_object(
    'canonical_user', pg_catalog.to_jsonb(v_canonical),
    'source_user', case when p_source_user_id is null then null else pg_catalog.to_jsonb(v_source) end,
    'user_devices',(
      select coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(d) order by d.id),'[]'::jsonb)
      from public.tepiha_user_devices d
      where d.user_id=p_canonical_user_id or d.user_id=p_source_user_id
    ),
    'device_approvals',(
      select coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(a) order by a.id),'[]'::jsonb)
      from public.tepiha_device_approvals a
      where a.pin=any(v_old_pins || array[v_canonical.pin])
    ),
    'employment_terms',(
      select coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(t) order by t.effective_from),'[]'::jsonb)
      from public.worker_employment_terms t
      where t.user_id=p_canonical_user_id or t.user_id=p_source_user_id
    ),
    'financial_checksum', v_before_checksum
  );

  if p_source_user_id is not null then
    if exists (
      select 1
      from public.tepiha_user_devices s
      join public.tepiha_user_devices c
        on c.user_id = p_canonical_user_id
       and c.device_id = s.device_id
      where s.user_id = p_source_user_id
    ) then raise exception 'STAFF_DEVICE_LINK_CONFLICT'; end if;

    delete from public.worker_employment_terms s
    using public.worker_employment_terms c
    where s.user_id = p_source_user_id
      and c.user_id = p_canonical_user_id
      and c.effective_from = s.effective_from
      and (pg_catalog.to_jsonb(s) - array['id','user_id','created_at']::text[])
          is not distinct from (pg_catalog.to_jsonb(c) - array['id','user_id','created_at']::text[]);

    update public.worker_employment_terms set user_id = p_canonical_user_id
    where user_id = p_source_user_id;

    -- Preserve each device row's actual is_approved flag. Only identity linkage changes.
    update public.tepiha_user_devices
    set user_id = p_canonical_user_id, requested_pin = v_canonical.pin
    where user_id = p_source_user_id;

    update private.staff_pin_aliases
    set canonical_user_id=p_canonical_user_id,
        current_pin_snapshot=v_canonical.pin
    where canonical_user_id=p_source_user_id;
  end if;

  v_history := private.canonicalize_staff_history_v1(
    p_canonical_user_id, v_old_pins, v_canonical.pin, v_source_ids
  );

  if p_source_user_id is not null then
    delete from public.users where id = p_source_user_id;
    if not found then raise exception 'STAFF_SOURCE_DELETE_FAILED'; end if;
  end if;

  foreach v_alias in array v_old_pins loop
    insert into private.staff_pin_aliases(
      alias_pin, canonical_user_id, current_pin_snapshot, source_user_id,
      reason, created_by_pin
    ) values (
      v_alias, p_canonical_user_id, v_canonical.pin, p_source_user_id,
      case when p_source_user_id is null then 'PIN_ROTATION_HISTORY' else 'DUPLICATE_USER_MERGE' end,
      v_actor.pin
    )
    on conflict (alias_pin) do update
      set current_pin_snapshot = excluded.current_pin_snapshot,
          retired_at = coalesce(private.staff_pin_aliases.retired_at, pg_catalog.now()),
          reason = excluded.reason,
          created_by_pin = excluded.created_by_pin
      where private.staff_pin_aliases.canonical_user_id = excluded.canonical_user_id;
  end loop;

  v_after_checksum := private.staff_financial_checksum_v1(array[v_canonical.pin]);
  if v_after_checksum is distinct from v_before_checksum then
    raise exception 'STAFF_FINANCIAL_CHECKSUM_MISMATCH before=% after=%', v_before_checksum, v_after_checksum;
  end if;

  select * into v_canonical from public.users u where u.id = p_canonical_user_id;
  v_after := pg_catalog.jsonb_build_object(
    'canonical_user', pg_catalog.to_jsonb(v_canonical),
    'source_deleted', p_source_user_id is null or not exists(select 1 from public.users u where u.id=p_source_user_id),
    'user_devices',(
      select coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(d) order by d.id),'[]'::jsonb)
      from public.tepiha_user_devices d where d.user_id=p_canonical_user_id
    ),
    'device_approvals',(
      select coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(a) order by a.id),'[]'::jsonb)
      from public.tepiha_device_approvals a where a.pin=v_canonical.pin
    ),
    'employment_terms',(
      select coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(t) order by t.effective_from),'[]'::jsonb)
      from public.worker_employment_terms t where t.user_id=p_canonical_user_id
    ),
    'financial_checksum', v_after_checksum,
    'history', v_history
  );
  v_result := pg_catalog.jsonb_build_object(
    'ok', true, 'action', case when p_source_user_id is null then 'CANONICALIZE' else 'MERGE' end,
    'canonical_user_id', p_canonical_user_id, 'pin', v_canonical.pin,
    'retired_pins', v_old_pins, 'source_user_id', p_source_user_id,
    'history', v_history, 'idempotency_key', p_idempotency_key
  );

  insert into private.staff_identity_merge_log(
    idempotency_key, action, canonical_user_id, source_user_id, old_pins,
    new_pin, actor_pin, request_payload, before_snapshot, after_snapshot, result
  ) values (
    p_idempotency_key,
    case when p_source_user_id is null then 'CANONICALIZE' else 'MERGE' end,
    p_canonical_user_id, p_source_user_id, v_old_pins, v_canonical.pin,
    v_actor.pin, v_request, v_before, v_after, v_result
  );

  return v_result;
end;
$$;

revoke execute on function public.merge_staff_identity_v1(text,uuid,uuid,text,text,text[],text)
from public, anon, authenticated;
grant execute on function public.merge_staff_identity_v1(text,uuid,uuid,text,text,text[],text)
to service_role;

comment on function public.merge_staff_identity_v1(text,uuid,uuid,text,text,text[],text) is
  'Service-role-only explicit UUID merge/canonicalization with stale checks, aliases, checksums and idempotent retries.';

create or replace function public.save_staff_identity_v1(
  p_actor_pin text,
  p_action text,
  p_user_id uuid default null,
  p_name text default null,
  p_role text default null,
  p_pin text default null,
  p_is_active boolean default null,
  p_patch jsonb default '{}'::jsonb,
  p_reactivate_user_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor public.users%rowtype;
  v_before public.users%rowtype;
  v_after public.users%rowtype;
  v_existing private.staff_identity_merge_log%rowtype;
  v_action text := pg_catalog.upper(pg_catalog.btrim(coalesce(p_action,'')));
  v_name text := pg_catalog.btrim(coalesce(p_name,''));
  v_role text := pg_catalog.upper(pg_catalog.btrim(coalesce(p_role,'')));
  v_pin text := pg_catalog.btrim(coalesce(p_pin,''));
  v_target_id uuid;
  v_idempotency_key text := pg_catalog.btrim(coalesce(p_patch->>'idempotency_key',''));
  v_expected_pin text := nullif(pg_catalog.btrim(coalesce(p_patch->>'expected_current_pin','')), '');
  v_expected_updated_at timestamptz;
  v_request jsonb;
  v_result jsonb;
  v_history jsonb := '{}'::jsonb;
  v_bad_key text;
  v_old_pin text;
  v_effective_name text;
  v_actor_rank integer := 0;
  v_target_rank integer := 0;
  v_requested_rank integer := 0;
begin
  if v_action not in ('CREATE','UPDATE','DEACTIVATE','REACTIVATE') then
    raise exception 'STAFF_ACTION_INVALID:%', v_action;
  end if;
  if v_idempotency_key = '' then raise exception 'STAFF_IDEMPOTENCY_KEY_REQUIRED'; end if;

  select key into v_bad_key
  from pg_catalog.jsonb_object_keys(coalesce(p_patch,'{}'::jsonb)) key
  where key not in (
    'idempotency_key','expected_current_pin','expected_updated_at',
    'salary','avans_manual','borxh_afatgjat','salary_day','bonus_transport','bonus_ushqim',
    'is_hybrid_transport','commission_rate_m2','pay_salary_enabled','pay_meal_enabled',
    'pay_meal_amount','pay_commission_enabled','pay_commission_rate_m2',
    'pay_transport_bonus_enabled','pay_transport_bonus_amount','pay_ready_bonus_enabled',
    'pay_cash_mode','pay_notes'
  ) limit 1;
  if v_bad_key is not null then raise exception 'STAFF_PATCH_KEY_NOT_ALLOWED:%', v_bad_key; end if;

  if nullif(p_patch->>'expected_updated_at','') is not null then
    begin v_expected_updated_at := (p_patch->>'expected_updated_at')::timestamptz;
    exception when others then raise exception 'STAFF_EXPECTED_UPDATED_AT_INVALID'; end;
  end if;

  select * into v_actor
  from public.users u
  where u.pin = pg_catalog.btrim(coalesce(p_actor_pin,'')) and u.is_active is true
  limit 1;
  v_actor_rank := private.staff_role_rank_v1(v_actor.role);
  if not found or v_actor_rank < 20 then raise exception 'STAFF_MANAGER_ONLY'; end if;

  v_target_id := case when v_action='REACTIVATE' then p_reactivate_user_id else p_user_id end;
  if v_action <> 'CREATE' and v_target_id is null then raise exception 'STAFF_EXPLICIT_USER_ID_REQUIRED'; end if;
  if v_action='REACTIVATE' and p_reactivate_user_id is null then raise exception 'STAFF_REACTIVATE_USER_ID_REQUIRED'; end if;

  v_request := pg_catalog.jsonb_build_object(
    'action',v_action,'user_id',p_user_id,'reactivate_user_id',p_reactivate_user_id,
    'name',p_name,'role',p_role,'pin',p_pin,'is_active',p_is_active,
    'patch',coalesce(p_patch,'{}'::jsonb) - 'idempotency_key'
  );
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('staff_identity_idem:' || v_idempotency_key,0)
  );
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('staff_identity_pin_registry_v1',0)
  );
  select * into v_existing from private.staff_identity_merge_log l where l.idempotency_key=v_idempotency_key;
  if found then
    if v_existing.action <> v_action or v_existing.request_payload is distinct from v_request then
      raise exception 'STAFF_IDEMPOTENCY_CONFLICT';
    end if;
    return v_existing.result;
  end if;

  if v_action='CREATE' then
    if v_name='' then raise exception 'STAFF_NAME_REQUIRED'; end if;
    if v_role='' then raise exception 'STAFF_ROLE_REQUIRED'; end if;
    v_requested_rank := private.staff_role_rank_v1(v_role);
    if v_requested_rank<0 then raise exception 'STAFF_ROLE_INVALID'; end if;
    if v_requested_rank>v_actor_rank then raise exception 'STAFF_ROLE_HIERARCHY_DENIED'; end if;
    if v_pin !~ '^[0-9]{3,12}$' then raise exception 'STAFF_PIN_INVALID'; end if;
    if exists (select 1 from private.staff_pin_aliases a where a.alias_pin=v_pin) then
      raise exception 'STAFF_PIN_IS_RETIRED:%',v_pin;
    end if;
    perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
      'staff_identity_name:' || private.staff_normalize_name_v1(v_name),0
    ));
    if exists (
      select 1 from public.users u
      where private.staff_normalize_name_v1(u.name)=private.staff_normalize_name_v1(v_name)
    ) then raise exception 'STAFF_NAME_MATCH_REQUIRES_REACTIVATION'; end if;

    if p_user_id is null then
      insert into public.users(name,role,pin,is_active)
      values (v_name,v_role,v_pin,coalesce(p_is_active,true))
      returning * into v_after;
    else
      insert into public.users(id,name,role,pin,is_active)
      values (p_user_id,v_name,v_role,v_pin,coalesce(p_is_active,true))
      returning * into v_after;
    end if;
    v_target_id := v_after.id;
  else
    perform pg_catalog.pg_advisory_xact_lock(
      pg_catalog.hashtextextended('staff_identity_user:' || v_target_id::text,0)
    );
    select * into v_before from public.users u where u.id=v_target_id for update;
    if not found then raise exception 'STAFF_USER_NOT_FOUND:%',v_target_id; end if;
    v_target_rank := private.staff_role_rank_v1(v_before.role);
    if v_target_rank>v_actor_rank then raise exception 'STAFF_ROLE_HIERARCHY_DENIED'; end if;
    if v_target_id=v_actor.id and v_action='DEACTIVATE' then
      raise exception 'STAFF_SELF_DEACTIVATE_NOT_ALLOWED';
    end if;
    if v_target_id=v_actor.id and v_role<>''
       and pg_catalog.upper(pg_catalog.btrim(v_role))
           <>pg_catalog.upper(pg_catalog.btrim(coalesce(v_before.role,''))) then
      raise exception 'STAFF_SELF_ROLE_CHANGE_NOT_ALLOWED';
    end if;
    if v_role<>'' then
      v_requested_rank := private.staff_role_rank_v1(v_role);
      if v_requested_rank<0 then raise exception 'STAFF_ROLE_INVALID'; end if;
      if v_requested_rank>v_actor_rank then raise exception 'STAFF_ROLE_HIERARCHY_DENIED'; end if;
    end if;
    if v_expected_pin is not null and v_before.pin is distinct from v_expected_pin then
      raise exception 'STAFF_CURRENT_PIN_STALE expected=% actual=%',v_expected_pin,v_before.pin;
    end if;
    if v_expected_updated_at is not null and v_before.updated_at is distinct from v_expected_updated_at then
      raise exception 'STAFF_UPDATED_AT_STALE expected=% actual=%',v_expected_updated_at,v_before.updated_at;
    end if;
    if v_action='UPDATE' and v_before.is_active is not true then raise exception 'STAFF_USE_REACTIVATE_ACTION'; end if;
    if v_action='REACTIVATE' and v_before.is_active is true then raise exception 'STAFF_USER_ALREADY_ACTIVE'; end if;
    if v_action='UPDATE' and p_is_active is false then raise exception 'STAFF_USE_DEACTIVATE_ACTION'; end if;
    if v_action='DEACTIVATE' and (
      v_name<>'' or v_role<>'' or v_pin<>'' or p_is_active is true
      or (coalesce(p_patch,'{}'::jsonb)
          - 'idempotency_key' - 'expected_current_pin' - 'expected_updated_at') <> '{}'::jsonb
    ) then raise exception 'STAFF_DEACTIVATE_ONLY_ACTION'; end if;

    v_effective_name := case when v_name<>'' then v_name else v_before.name end;
    if v_action in ('UPDATE','REACTIVATE') then
      perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
        'staff_identity_name:' || private.staff_normalize_name_v1(v_effective_name),0
      ));
    end if;
    if v_action in ('UPDATE','REACTIVATE') and exists (
      select 1 from public.users u
      where u.id<>v_target_id
        and private.staff_normalize_name_v1(u.name)=private.staff_normalize_name_v1(v_effective_name)
    ) then raise exception 'STAFF_NAME_MATCH_REQUIRES_REACTIVATION'; end if;

    v_old_pin := v_before.pin;
    if v_pin<>'' and v_pin<>v_old_pin then
      if v_pin !~ '^[0-9]{3,12}$' then raise exception 'STAFF_PIN_INVALID'; end if;
      if exists (select 1 from public.users u where u.pin=v_pin and u.id<>v_target_id) then
        raise exception 'STAFF_PIN_ALREADY_USED:%',v_pin;
      end if;
      if exists (select 1 from private.staff_pin_aliases a where a.alias_pin=v_pin) then
        raise exception 'STAFF_PIN_IS_RETIRED:%',v_pin;
      end if;
      if exists (
        select 1 from public.offline_code_leases l
        where l.owner_id=v_old_pin and l.status in ('available','assigned')
          and (l.expires_at is null or l.expires_at>pg_catalog.now())
      ) then raise exception 'STAFF_ACTIVE_OFFLINE_LEASE_CONFLICT'; end if;
      if exists (
        select 1 from public.base_code_pool b
        where (b.owner_id=v_old_pin or b.reserved_by=v_old_pin)
          and b.status='reserved'
          and (b.lease_expires_at is null or b.lease_expires_at>pg_catalog.now())
      ) then raise exception 'STAFF_ACTIVE_BASE_RESERVATION_CONFLICT'; end if;

    else
      v_pin := v_old_pin;
    end if;

    update public.users u set
      name=case when v_name<>'' then v_name else u.name end,
      role=case when v_role<>'' then v_role else u.role end,
      pin=v_pin,
      is_active=case when v_action='DEACTIVATE' then false when v_action='REACTIVATE' then true else coalesce(p_is_active,u.is_active) end
    where u.id=v_target_id
    returning * into v_after;

    if v_pin<>v_old_pin then
      v_history := private.canonicalize_staff_history_v1(v_target_id,array[v_old_pin],v_pin,'{}'::uuid[]);
      update private.staff_pin_aliases
      set current_pin_snapshot=v_pin
      where canonical_user_id=v_target_id;
      insert into private.staff_pin_aliases(alias_pin,canonical_user_id,current_pin_snapshot,source_user_id,reason,created_by_pin)
      values(v_old_pin,v_target_id,v_pin,v_target_id,'PIN_ROTATION',v_actor.pin);
    end if;
  end if;

  update public.users u set
    salary=case when p_patch?'salary' then (p_patch->>'salary')::numeric else u.salary end,
    avans_manual=case when p_patch?'avans_manual' then (p_patch->>'avans_manual')::numeric else u.avans_manual end,
    borxh_afatgjat=case when p_patch?'borxh_afatgjat' then (p_patch->>'borxh_afatgjat')::numeric else u.borxh_afatgjat end,
    salary_day=case when p_patch?'salary_day' then nullif(p_patch->>'salary_day','')::integer else u.salary_day end,
    bonus_transport=case when p_patch?'bonus_transport' then (p_patch->>'bonus_transport')::numeric else u.bonus_transport end,
    bonus_ushqim=case when p_patch?'bonus_ushqim' then (p_patch->>'bonus_ushqim')::numeric else u.bonus_ushqim end,
    is_hybrid_transport=case when p_patch?'is_hybrid_transport' then (p_patch->>'is_hybrid_transport')::boolean else u.is_hybrid_transport end,
    commission_rate_m2=case when p_patch?'commission_rate_m2' then (p_patch->>'commission_rate_m2')::numeric else u.commission_rate_m2 end,
    pay_salary_enabled=case when p_patch?'pay_salary_enabled' then (p_patch->>'pay_salary_enabled')::boolean else u.pay_salary_enabled end,
    pay_meal_enabled=case when p_patch?'pay_meal_enabled' then (p_patch->>'pay_meal_enabled')::boolean else u.pay_meal_enabled end,
    pay_meal_amount=case when p_patch?'pay_meal_amount' then (p_patch->>'pay_meal_amount')::numeric else u.pay_meal_amount end,
    pay_commission_enabled=case when p_patch?'pay_commission_enabled' then (p_patch->>'pay_commission_enabled')::boolean else u.pay_commission_enabled end,
    pay_commission_rate_m2=case when p_patch?'pay_commission_rate_m2' then (p_patch->>'pay_commission_rate_m2')::numeric else u.pay_commission_rate_m2 end,
    pay_transport_bonus_enabled=case when p_patch?'pay_transport_bonus_enabled' then (p_patch->>'pay_transport_bonus_enabled')::boolean else u.pay_transport_bonus_enabled end,
    pay_transport_bonus_amount=case when p_patch?'pay_transport_bonus_amount' then (p_patch->>'pay_transport_bonus_amount')::numeric else u.pay_transport_bonus_amount end,
    pay_ready_bonus_enabled=case when p_patch?'pay_ready_bonus_enabled' then (p_patch->>'pay_ready_bonus_enabled')::boolean else u.pay_ready_bonus_enabled end,
    pay_cash_mode=case when p_patch?'pay_cash_mode' then p_patch->>'pay_cash_mode' else u.pay_cash_mode end,
    pay_notes=case when p_patch?'pay_notes' then p_patch->>'pay_notes' else u.pay_notes end,
    pay_updated_at=case when p_patch-'idempotency_key'-'expected_current_pin'-'expected_updated_at'<>'{}'::jsonb then pg_catalog.now() else u.pay_updated_at end,
    pay_updated_by_pin=case when p_patch-'idempotency_key'-'expected_current_pin'-'expected_updated_at'<>'{}'::jsonb then v_actor.pin else u.pay_updated_by_pin end,
    pay_updated_by_name=case when p_patch-'idempotency_key'-'expected_current_pin'-'expected_updated_at'<>'{}'::jsonb then v_actor.name else u.pay_updated_by_name end
  where u.id=v_target_id
  returning * into v_after;

  v_result := pg_catalog.jsonb_build_object(
    'ok',true,'action',v_action,'user',pg_catalog.to_jsonb(v_after),
    'history',v_history,'idempotency_key',v_idempotency_key
  );
  insert into private.staff_identity_merge_log(
    idempotency_key,action,canonical_user_id,source_user_id,old_pins,new_pin,
    actor_pin,request_payload,before_snapshot,after_snapshot,result
  ) values (
    v_idempotency_key,v_action,v_target_id,null,
    case when v_old_pin is null or v_old_pin=v_after.pin then '{}'::text[] else array[v_old_pin] end,
    v_after.pin,v_actor.pin,v_request,
    case when v_before.id is null then '{}'::jsonb else pg_catalog.to_jsonb(v_before) end,
    pg_catalog.to_jsonb(v_after),v_result
  );
  return v_result;
end;
$$;

revoke execute on function public.save_staff_identity_v1(text,text,uuid,text,text,text,boolean,jsonb,uuid)
from public, anon, authenticated;
grant execute on function public.save_staff_identity_v1(text,text,uuid,text,text,text,boolean,jsonb,uuid)
to service_role;

comment on function public.save_staff_identity_v1(text,text,uuid,text,text,text,boolean,jsonb,uuid) is
  'Service-role-only staff CREATE/UPDATE/DEACTIVATE/REACTIVATE. UUID-explicit mutations, stale guards, name collision guard, retired-PIN reservation and idempotency.';

-- Preserve the existing public bonus-opportunity access behavior while adding
-- DB-authenticated viewer identity for the Bujar-only motivational UI.
create or replace function public.get_base_bonus_opportunities_v1(p_actor_pin text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor public.users%rowtype;
  v_config public.base_ready_bonus_config%rowtype;
  v_result jsonb;
begin
  select * into v_actor
  from public.users
  where pin=pg_catalog.btrim(coalesce(p_actor_pin,'')) and is_active is true
  limit 1;
  if not found then raise exception 'BONUS_ACTOR_NOT_FOUND'; end if;
  if pg_catalog.upper(coalesce(v_actor.role,'')) not in (
    'PUNTOR','PUNETOR','WORKER','BAZIST','BASE','DISPATCH','ADMIN','ADMIN_MASTER',
    'MASTER','MASTER USER','OWNER','PRONAR','SUPERADMIN'
  ) then raise exception 'BONUS_ACCESS_DENIED'; end if;

  select * into v_config from public.base_ready_bonus_config where id=1;
  if not found then raise exception 'BASE_READY_BONUS_CONFIG_MISSING'; end if;

  with candidates as (
    select
      o.id as order_id,o.code as order_code,o.client_name,o.client_phone,
      pg_catalog.lower(coalesce(o.status,'')) as status,
      pg_catalog.round(coalesce(public.tepiha_daily_order_m2(o.data,o.m2_total),0)::numeric,2) as m2,
      pg_catalog.round(greatest(
        coalesce(o.price_total,0),coalesce(o.total,0),
        case when coalesce(o.data#>>'{pay,euro}','') ~ '^-?[0-9]+(\.[0-9]+)?$'
          then (o.data#>>'{pay,euro}')::numeric else 0 end
      ),2) as total,
      pg_catalog.round(greatest(
        coalesce(o.paid,0),coalesce(o.paid_cash,0),
        case when coalesce(o.data#>>'{pay,paid}','') ~ '^-?[0-9]+(\.[0-9]+)?$'
          then (o.data#>>'{pay,paid}')::numeric else 0 end,
        case when coalesce(o.data->>'clientPaid','') ~ '^-?[0-9]+(\.[0-9]+)?$'
          then (o.data->>'clientPaid')::numeric else 0 end
      ),2) as paid,
      o.created_at,o.ready_at,
      pg_catalog.round(greatest(0,
        extract(epoch from ((o.created_at + pg_catalog.make_interval(hours => v_config.window_hours::int))-pg_catalog.now()))/3600
      )::numeric,2) as hours_left,
      o.created_at + pg_catalog.make_interval(hours => v_config.window_hours::int) as deadline_at,
      pg_catalog.round(coalesce(public.tepiha_daily_order_m2(o.data,o.m2_total),0)::numeric * coalesce(v_config.rate_m2,0),2) as potential_bonus,
      b.id as bonus_id,b.eligible as bonus_eligible,b.status as bonus_status,b.worker_pin as bonus_worker_pin
    from public.orders o
    left join public.base_ready_bonuses b on b.order_id=o.id
    where coalesce(v_config.enabled,false)
      and o.created_at + pg_catalog.make_interval(hours => v_config.window_hours::int) > pg_catalog.now()
      and pg_catalog.lower(coalesce(o.status,'')) in ('pranim','pastrim','gati')
      and not public.base_order_is_fully_paid_v2(o.data,o.price_total,o.paid,o.paid_cash)
      and coalesce(public.tepiha_daily_order_m2(o.data,o.m2_total),0) > 0
  )
  select pg_catalog.jsonb_build_object(
    'ok',true,'generated_at',pg_catalog.now(),
    'viewer',pg_catalog.jsonb_build_object('user_id',v_actor.id,'pin',v_actor.pin,'name',v_actor.name),
    'config',pg_catalog.jsonb_build_object(
      'enabled',v_config.enabled,'window_hours',v_config.window_hours,
      'rate_m2',v_config.rate_m2,'effective_from',v_config.effective_from
    ),
    'rows',coalesce(pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object(
      'order_id',order_id,'order_code',order_code,'client_name',client_name,'client_phone',client_phone,
      'status',status,'m2',m2,'total',total,'paid',paid,'debt',pg_catalog.round(greatest(0,total-paid),2),
      'created_at',created_at,'ready_at',ready_at,'hours_left',hours_left,'deadline_at',deadline_at,
      'potential_bonus',potential_bonus,'bonus_id',bonus_id,'bonus_eligible',bonus_eligible,
      'bonus_status',bonus_status,'bonus_worker_pin',bonus_worker_pin
    ) order by hours_left asc,order_code asc),'[]'::jsonb)
  ) into v_result from candidates;
  return v_result;
end;
$$;

-- Keep the pre-existing caller set; this RPC is part of the signed PIN UI flow.
grant execute on function public.get_base_bonus_opportunities_v1(text)
to public, anon, authenticated, service_role;

-- Discover the known repairs from durable evidence. Current PINs and UUIDs are
-- deliberately not embedded in the migration: users.id/current pin are read
-- under lock, Bujar's retired PIN is proven by the preserved backup row, and
-- Blerim's oldest PIN is proven by its device history.
do $canonical_staff_repair$
declare
  v_actor public.users%rowtype;
  v_bujar public.users%rowtype;
  v_blerim public.users%rowtype;
  v_blerim_source public.users%rowtype;
  v_bujar_id uuid;
  v_blerim_id uuid;
  v_blerim_source_id uuid;
  v_count integer;
  v_bujar_retired_pin constant text := '5555';
  v_blerim_retired_pin constant text := '6666';
  v_blerim_device_pin constant text := '8888';
begin
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('staff_identity_pin_registry_v1',0)
  );
  select pg_catalog.count(*) into v_count
  from public.users u
  where u.is_active is true and u.is_master is true
    and pg_catalog.upper(coalesce(u.role,'')) in (
      'ADMIN','ADMIN_MASTER','OWNER','PRONAR','SUPERADMIN','MASTER','MASTER USER','MASTER_USER'
    );
  if v_count<>1 then raise exception 'STAFF_REPAIR_MANAGER_NOT_UNIQUE:%',v_count; end if;
  select * into v_actor
  from public.users u
  where u.is_active is true and u.is_master is true
    and pg_catalog.upper(coalesce(u.role,'')) in (
      'ADMIN','ADMIN_MASTER','OWNER','PRONAR','SUPERADMIN','MASTER','MASTER USER','MASTER_USER'
    )
  for update;

  select pg_catalog.count(*) into v_count
  from public.backup_bujar_oruqi_sleeping_20260614_v2 b
  join public.users u on u.id=b.id
  where b.pin=v_bujar_retired_pin and u.pin<>b.pin and u.is_active is true
    and private.staff_normalize_name_v1(u.name)=private.staff_normalize_name_v1(b.name)
    and pg_catalog.upper(pg_catalog.btrim(coalesce(u.role,'')))
      =pg_catalog.upper(pg_catalog.btrim(coalesce(b.role,'')));
  if v_count<>1 then raise exception 'STAFF_REPAIR_BUJAR_BACKUP_PROOF_FAILED:%',v_count; end if;
  select u.* into v_bujar
  from public.backup_bujar_oruqi_sleeping_20260614_v2 b
  join public.users u on u.id=b.id
  where b.pin=v_bujar_retired_pin and u.pin<>b.pin and u.is_active is true
    and private.staff_normalize_name_v1(u.name)=private.staff_normalize_name_v1(b.name)
    and pg_catalog.upper(pg_catalog.btrim(coalesce(u.role,'')))
      =pg_catalog.upper(pg_catalog.btrim(coalesce(b.role,'')))
  for update of u;
  v_bujar_id := v_bujar.id;

  select pg_catalog.count(*) into v_count
  from public.users u
  where u.pin=v_blerim_retired_pin and u.is_active is false;
  if v_count>1 then raise exception 'STAFF_REPAIR_BLERIM_SOURCE_NOT_UNIQUE:%',v_count; end if;

  if v_count=1 then
    select * into v_blerim_source
    from public.users u
    where u.pin=v_blerim_retired_pin and u.is_active is false
    for update;
    v_blerim_source_id := v_blerim_source.id;

    select pg_catalog.count(*) into v_count
    from public.users u
    where u.id<>v_blerim_source.id and u.is_active is true
      and private.staff_normalize_name_v1(u.name)=private.staff_normalize_name_v1(v_blerim_source.name)
      and pg_catalog.upper(pg_catalog.btrim(coalesce(u.role,'')))
        =pg_catalog.upper(pg_catalog.btrim(coalesce(v_blerim_source.role,'')));
    if v_count<>1 then raise exception 'STAFF_REPAIR_BLERIM_CANONICAL_NOT_UNIQUE:%',v_count; end if;
    select * into v_blerim
    from public.users u
    where u.id<>v_blerim_source.id and u.is_active is true
      and private.staff_normalize_name_v1(u.name)=private.staff_normalize_name_v1(v_blerim_source.name)
      and pg_catalog.upper(pg_catalog.btrim(coalesce(u.role,'')))
        =pg_catalog.upper(pg_catalog.btrim(coalesce(v_blerim_source.role,'')))
    for update;

    if not exists(
      select 1
      from public.tepiha_device_approvals a
      join public.tepiha_user_devices d
        on d.user_id=v_blerim_source.id and d.device_id=a.device_id
      where a.pin=v_blerim_device_pin and d.requested_pin=v_blerim_device_pin
    ) then raise exception 'STAFF_REPAIR_BLERIM_DEVICE_HISTORY_PROOF_FAILED'; end if;
  else
    select a.source_user_id into v_blerim_source_id
    from private.staff_pin_aliases a
    where a.alias_pin=v_blerim_retired_pin;
    if v_blerim_source_id is null then raise exception 'STAFF_REPAIR_BLERIM_SOURCE_PROOF_MISSING'; end if;

    select u.* into v_blerim
    from private.staff_pin_aliases a
    join public.users u on u.id=a.canonical_user_id
    where a.alias_pin=v_blerim_retired_pin and u.is_active is true;
    if not found then raise exception 'STAFF_REPAIR_BLERIM_CANONICAL_ALIAS_MISSING'; end if;
    if not exists(
      select 1 from private.staff_pin_aliases a
      where a.alias_pin=v_blerim_device_pin and a.canonical_user_id=v_blerim.id
    ) then raise exception 'STAFF_REPAIR_BLERIM_DEVICE_ALIAS_MISSING'; end if;
    if not exists(
      select 1 from private.staff_identity_merge_log l
      where l.idempotency_key='CANONICAL_STAFF_IDENTITY_V1:BLERIM:DUPLICATE_MERGE'
        and l.source_user_id=v_blerim_source_id and l.canonical_user_id=v_blerim.id
    ) then raise exception 'STAFF_REPAIR_BLERIM_MERGE_PROOF_MISSING'; end if;
  end if;

  if v_bujar.pin=any(array[v_bujar_retired_pin,v_blerim_retired_pin,v_blerim_device_pin])
     or v_blerim.pin=any(array[v_bujar_retired_pin,v_blerim_retired_pin,v_blerim_device_pin]) then
    raise exception 'STAFF_REPAIR_CURRENT_PIN_IS_RETIRED';
  end if;
  v_blerim_id := v_blerim.id;

  perform public.merge_staff_identity_v1(
    v_actor.pin,v_bujar_id,null,v_bujar.pin,null,array[v_bujar_retired_pin]::text[],
    'CANONICAL_STAFF_IDENTITY_V1:BUJAR:RETIRED_PIN_HISTORY'
  );
  perform public.merge_staff_identity_v1(
    v_actor.pin,v_blerim_id,v_blerim_source_id,v_blerim.pin,v_blerim_retired_pin,
    array[v_blerim_retired_pin,v_blerim_device_pin]::text[],
    'CANONICAL_STAFF_IDENTITY_V1:BLERIM:DUPLICATE_MERGE'
  );

  select * into v_bujar from public.users where id=v_bujar_id;
  select * into v_blerim from public.users where id=v_blerim_id;
  if v_bujar.is_active is not true or v_blerim.is_active is not true then
    raise exception 'STAFF_POSTCHECK_CANONICAL_USER_INACTIVE';
  end if;
  if exists(
    select 1 from public.users
    where pin=any(array[v_bujar_retired_pin,v_blerim_retired_pin,v_blerim_device_pin])
  ) then raise exception 'STAFF_POSTCHECK_RETIRED_PIN_STILL_CURRENT'; end if;
  if exists(select 1 from public.users where id=v_blerim_source_id) then
    raise exception 'STAFF_POSTCHECK_BLERIM_SOURCE_STILL_EXISTS';
  end if;
  if (select pg_catalog.count(*) from public.users u
      where private.staff_normalize_name_v1(u.name)=private.staff_normalize_name_v1(v_bujar.name))<>1
     or (select pg_catalog.count(*) from public.users u
      where private.staff_normalize_name_v1(u.name)=private.staff_normalize_name_v1(v_blerim.name))<>1 then
    raise exception 'STAFF_POSTCHECK_NORMALIZED_NAME_NOT_UNIQUE';
  end if;
  if not exists(
    select 1 from private.staff_pin_aliases a
    where a.alias_pin=v_bujar_retired_pin and a.canonical_user_id=v_bujar.id
      and a.current_pin_snapshot=v_bujar.pin
  ) or (select pg_catalog.count(*) from private.staff_pin_aliases a
        where a.alias_pin in (v_blerim_retired_pin,v_blerim_device_pin)
          and a.canonical_user_id=v_blerim.id and a.current_pin_snapshot=v_blerim.pin)<>2 then
    raise exception 'STAFF_POSTCHECK_ALIAS_MAPPING_FAILED';
  end if;

  if exists(
    select 1 from public.tepiha_user_devices d
    where d.user_id=v_blerim_source_id
      or d.requested_pin=any(array[v_bujar_retired_pin,v_blerim_retired_pin,v_blerim_device_pin])
  ) then raise exception 'STAFF_POSTCHECK_DEVICE_IDENTITY_FAILED'; end if;
  if exists(
    select 1 from public.tepiha_device_approvals a
    where a.pin=any(array[v_bujar_retired_pin,v_blerim_retired_pin,v_blerim_device_pin])
  ) then raise exception 'STAFF_POSTCHECK_DEVICE_APPROVAL_PIN_FAILED'; end if;
  if exists(
    select 1
    from public.tepiha_device_approvals a
    left join public.tepiha_user_devices d
      on d.device_id=a.device_id
     and d.user_id=case when a.pin=v_bujar.pin then v_bujar.id else v_blerim.id end
    where a.pin in (v_bujar.pin,v_blerim.pin)
      and a.approved is distinct from coalesce(d.is_approved,false)
  ) then raise exception 'STAFF_POSTCHECK_DEVICE_APPROVAL_ELEVATION'; end if;
  if exists(select 1 from public.payroll_month_close_items where worker_id=v_blerim_source_id)
     or exists(select 1 from public.worker_employment_terms where user_id=v_blerim_source_id) then
    raise exception 'STAFF_POSTCHECK_UUID_REFERENCE_FAILED';
  end if;

  if exists(
    select 1 from public.base_code_pool b
    where b.owner_id=any(array[v_bujar_retired_pin,v_blerim_retired_pin,v_blerim_device_pin])
       or b.reserved_by=any(array[v_bujar_retired_pin,v_blerim_retired_pin,v_blerim_device_pin])
       or b.used_by_pin=any(array[v_bujar_retired_pin,v_blerim_retired_pin,v_blerim_device_pin])
  ) then raise exception 'STAFF_POSTCHECK_BASE_POOL_IDENTITY_FAILED'; end if;
  if exists(
    select 1 from public.offline_code_leases l
    where l.owner_id=any(
      array[v_bujar_retired_pin,v_blerim_retired_pin,v_blerim_device_pin,v_blerim_source_id::text]
    )
  ) then raise exception 'STAFF_POSTCHECK_OFFLINE_LEASE_IDENTITY_FAILED'; end if;
  if exists(
    select 1 from public.transport_code_pool t
    where t.owner_id=any(
      array[v_bujar_retired_pin,v_blerim_retired_pin,v_blerim_device_pin,v_blerim_source_id::text]
    )
  ) then raise exception 'STAFF_POSTCHECK_TRANSPORT_POOL_IDENTITY_FAILED'; end if;

  if exists(
    select 1 from public.orders o
    where o.data is distinct from private.staff_identity_json_canonicalize_v1(
      o.data,array[v_bujar_retired_pin],v_bujar.pin,'{}'::text[],v_bujar.id::text
    ) or o.data is distinct from private.staff_identity_json_canonicalize_v1(
      o.data,array[v_blerim_retired_pin,v_blerim_device_pin],v_blerim.pin,
      array[v_blerim_source_id::text],v_blerim.id::text
    )
  ) then raise exception 'STAFF_POSTCHECK_ORDER_IDENTITY_FIELDS_FAILED'; end if;
  if exists(
    select 1 from public.transport_orders o
    where o.data is distinct from private.staff_identity_json_canonicalize_v1(
      o.data,array[v_bujar_retired_pin],v_bujar.pin,'{}'::text[],v_bujar.id::text
    ) or o.data is distinct from private.staff_identity_json_canonicalize_v1(
      o.data,array[v_blerim_retired_pin,v_blerim_device_pin],v_blerim.pin,
      array[v_blerim_source_id::text],v_blerim.id::text
    )
  ) then raise exception 'STAFF_POSTCHECK_TRANSPORT_IDENTITY_FIELDS_FAILED'; end if;

  if exists(
    select 1
    from (values ('anon'),('authenticated')) as r(role_name)
    cross join (values
      ('public.tepiha_user_devices'),('public.tepiha_device_approvals')
    ) as t(table_name)
    cross join (values ('SELECT'),('INSERT'),('UPDATE'),('DELETE')) as p(privilege_name)
    where pg_catalog.has_table_privilege(r.role_name,t.table_name,p.privilege_name)
  ) then raise exception 'STAFF_POSTCHECK_DEVICE_TABLE_ACL_FAILED'; end if;
  if exists(
    select 1 from public.users u
    where pg_catalog.btrim(coalesce(u.name,''))<>''
    group by private.staff_normalize_name_v1(u.name)
    having pg_catalog.count(*)>1
  ) then raise exception 'STAFF_POSTCHECK_ANY_NORMALIZED_NAME_DUPLICATE'; end if;
end;
$canonical_staff_repair$;

create unique index if not exists users_normalized_name_uq_v1
on public.users ((
  pg_catalog.lower(pg_catalog.regexp_replace(pg_catalog.btrim(coalesce(name,'')),'\s+',' ','g'))
))
where pg_catalog.btrim(coalesce(name,''))<>'';

comment on index public.users_normalized_name_uq_v1 is
  'One durable staff identity per exact case/whitespace-normalized name; reactivation must target its UUID.';

-- Internal helpers are intentionally unavailable through the Data API.
revoke execute on function private.staff_normalize_name_v1(text) from public, anon, authenticated;
revoke execute on function private.staff_role_rank_v1(text) from public, anon, authenticated;
revoke execute on function private.staff_identity_json_canonicalize_v1(jsonb,text[],text,text[],text) from public, anon, authenticated;
revoke execute on function private.staff_update_pin_column_if_present_v1(text,text,text[],text) from public, anon, authenticated;
revoke execute on function private.staff_financial_checksum_v1(text[]) from public, anon, authenticated;
revoke execute on function private.canonicalize_staff_history_v1(uuid,text[],text,uuid[]) from public, anon, authenticated;
revoke execute on function private.set_staff_user_updated_at_v1() from public, anon, authenticated;
revoke execute on function private.guard_staff_pin_alias_v1() from public, anon, authenticated;
revoke execute on function private.guard_staff_current_pin_reuse_v1() from public, anon, authenticated;
