-- ADDITIVE ONLY: stable DB storage for monthly fixed/obligative expenses
create table if not exists public.company_fixed_expenses (
  id bigint generated by default as identity primary key,
  title text not null,
  amount numeric(12,2) not null default 0,
  due_day integer not null default 1 check (due_day between 1 and 31),
  essential boolean not null default true,
  active boolean not null default true,
  note text null,
  created_by_pin text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_company_fixed_expenses_active_due
  on public.company_fixed_expenses (active, due_day);

create or replace function public.set_company_fixed_expenses_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

DROP TRIGGER IF EXISTS trg_company_fixed_expenses_updated_at ON public.company_fixed_expenses;
create trigger trg_company_fixed_expenses_updated_at
before update on public.company_fixed_expenses
for each row
execute function public.set_company_fixed_expenses_updated_at();

alter table public.company_fixed_expenses enable row level security;

-- manager/admin roles can fully manage rows
DROP POLICY IF EXISTS company_fixed_expenses_select_auth ON public.company_fixed_expenses;
create policy company_fixed_expenses_select_auth
on public.company_fixed_expenses
for select
using (auth.role() = 'authenticated' or auth.role() = 'anon');

DROP POLICY IF EXISTS company_fixed_expenses_insert_auth ON public.company_fixed_expenses;
create policy company_fixed_expenses_insert_auth
on public.company_fixed_expenses
for insert
with check (auth.role() = 'authenticated' or auth.role() = 'anon');

DROP POLICY IF EXISTS company_fixed_expenses_update_auth ON public.company_fixed_expenses;
create policy company_fixed_expenses_update_auth
on public.company_fixed_expenses
for update
using (auth.role() = 'authenticated' or auth.role() = 'anon')
with check (auth.role() = 'authenticated' or auth.role() = 'anon');

DROP POLICY IF EXISTS company_fixed_expenses_delete_auth ON public.company_fixed_expenses;
create policy company_fixed_expenses_delete_auth
on public.company_fixed_expenses
for delete
using (auth.role() = 'authenticated' or auth.role() = 'anon');
