export const ARKA_PAYMENT_STATUS = {
  PENDING: 'PENDING',
  COLLECTED: 'COLLECTED',
  PENDING_DISPATCH_APPROVAL: 'PENDING_DISPATCH_APPROVAL',
  ACCEPTED_BY_DISPATCH: 'ACCEPTED_BY_DISPATCH',
  REJECTED: 'REJECTED',
  VOIDED: 'VOIDED',
  SALARY_PAID: 'SALARY_PAID',
  SETTLED_IN_SALARY: 'SETTLED_IN_SALARY',
};

export const ARKA_PAYMENT_TYPE = {
  IN: 'IN',
  TRANSPORT: 'TRANSPORT',
  EXPENSE: 'EXPENSE',
  TIMA: 'TIMA',
  MEAL_PAYMENT: 'MEAL_PAYMENT',
  MEAL_COVERED: 'MEAL_COVERED',
  SALARY_PAYMENT: 'SALARY_PAYMENT',
};

export const ARKA_SOURCE_MODULE = {
  BASE: 'BASE',
  TRANSPORT: 'TRANSPORT',
  ARKA: 'ARKA',
};

export const ARKA_ACTION = {
  BASE_ORDER_PAYMENT: 'BASE_ORDER_PAYMENT',
  TRANSPORT_ORDER_PAYMENT: 'TRANSPORT_ORDER_PAYMENT',
  EXPENSE_REQUEST: 'EXPENSE_REQUEST',
  CREATE_MEAL_DISTRIBUTION: 'CREATE_MEAL_DISTRIBUTION',
  COMPANY_BUDGET_SPEND: 'COMPANY_BUDGET_SPEND',
  SUBMIT_HANDOFF: 'SUBMIT_HANDOFF',
  ACCEPT_HANDOFF: 'ACCEPT_HANDOFF',
  REJECT_HANDOFF: 'REJECT_HANDOFF',
  VOID_OR_REVERSE_PAYMENT: 'VOID_OR_REVERSE_PAYMENT',
  PAYROLL_SALARY_PAYMENT: 'PAYROLL_SALARY_PAYMENT',
};

export const ARKA_ACTIVE_PAYMENT_STATUSES = [
  ARKA_PAYMENT_STATUS.PENDING,
  ARKA_PAYMENT_STATUS.COLLECTED,
  ARKA_PAYMENT_STATUS.PENDING_DISPATCH_APPROVAL,
  ARKA_PAYMENT_STATUS.ACCEPTED_BY_DISPATCH,
];

export const ARKA_HANDOFF_STATUS = {
  PENDING_DISPATCH_APPROVAL: 'PENDING_DISPATCH_APPROVAL',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
};

export function normalizeLegacyArkaStatus(status) {
  const raw = String(status || '').trim().toUpperCase();
  if (raw === 'HANDED') return ARKA_PAYMENT_STATUS.PENDING_DISPATCH_APPROVAL;
  return raw;
}
